[package]
name = "pocket-pirates"
version = "0.1.0"
authors = ["lcagustini <torresmon235@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.5"
ears = "*"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
default-features = false
features = ["image", "ttf"]
